### PR TITLE
Update managers to comply with strict typing

### PR DESCRIPTION
**Pull request by goakley**
Thank you for your time in looking at these changes.
I'm trying to work in manageable chunks to not spam the project with PRs.

---

Three changes are less trivial then just adding some typing code:

* The `AudioManager` works with specific types of audio that can be
  typed with string literals (instead of arbitrary strings).
* `StoryManager.setupStory` deferred initialising some class properties
  which allowed for potentially undefined values.
* Phaser is typed to accept "undefined" for unknown values, but was
  getting passed "null" in some places.

Otherwise, it's pretty standard typing fixes, some of which make the
code more crash-resistant:

* Avoid performing math or calling methods on `undefined`
* Convert some objects ({}) to mapped types ({string:value})
* Assign custom types to AudioManager properties
* Add explicit types to manager function definitions

### CODE REVIEW

**Comment by lunafromthemoon** [comment]
Thanks for all this new typing improvements! I left a review, about the music manager.

**Comment by goakley** [comment]
> Thanks for all this new typing improvements! I left a review, about the music manager.

Uh-oh, I don't see your comments for some reason!  Maybe they didn't get saved by GitHub?

**Comment by goakley** [comment]
@lunafromthemoon I rebased on main to pick up the lint changes, which now shows the problem with `'bgm' | 'bgs'` that I assume was part of your review that I couldn't find (sorry!)

From what I can tell, one piece of logic expects the audio channels to be either `'bgm'` or `'bgs'`, while the other logic expects them to be any arbitrary string as specified in the story yaml (e.g. `'morningBGM'` from `- play morningBGM`).  What is the correct behaviour here?

**Comment by lunafromthemoon** [comment]
The audio channels can now be any name the user wants, but by default it will be bgm. That's part of the review I was doing, sorry I took so long to answer, but yeah, this is the heart of the issue. I'll tag you on the reviews and see if you can see them!

**Comment by goakley** [comment]
Alright, I think I cracked it.

For the life of me I can't find the reviews on this PR.  Are they submitted to GitHub, or do you do reviews somewhere else?

**Comment by lunafromthemoon** [comment]
Hey @goakley the reviews are here! I even tag you in one to see if you could find it, but I guess not??? I have no idea why though. In any case, thanks so much for your collaboration! Great stuff!

**Pull request merged**
