### PR TITLE
chore: release process

### PR DESCRIPTION
**Pull request by seleb**
Adds release process which will automatically:

- bump version based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
- generate changelog based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
- build library + type definitions
- update docs/demos
- publish package on npm
- publish release on github
- push changes to github
- upload demo to itch.io

There are a number of steps that need to be taken before this can/should be merged:

- [x] create `main` branch from `master`
  - the automated release workflow is setup to only run on the `main` branch
- [x] manually create github release with tag `v2.2.1` (i.e. `v` + current version)
  - this is needed so that the automatic releases will start from the current version instead of `1.0.0`
- [x] add github secrets under https://github.com/lunafromthemoon/RenJS-V2/settings/secrets/actions
  - [x] `REPO_READ_TOKEN`
    - a github personal access token created for your account under https://github.com/settings/tokens with scope `public_repo` checked
    - this is needed in order for the CI to push the release commit and trigger the workflow that pushes to itch.io
  - [x] `NPM_TOKEN`
    - an npm access token created for your account on https://www.npmjs.com with type `Automation`
    - this is needed in order for the CI to publish releases to npm
  - [x] `BUTLER_CREDENTIALS`
    - an itch,io API key created for your account under https://itch.io/user/settings/api-keys
    - this is needed in order for the CI to push builds to your itch.io projects
- [x] sort out `docs`/itch.io build
  - added rough version of what a `/docs` + tutorial demo build could look like, but will need the full docs site copy to write the proper automation for those

### CODE REVIEW

**Comment by lunafromthemoon** [comment]
Hello hello, I did many of the tasks here, like creating the new main branch (and making it the default branch), adding the secrets, adding the docs.

How does it work with the docs? Is it possible to directly serve the pages from one folder in the main branch, or will the process include pushing the changes there to a different branch (like gh_pages) and then I can point the renjs.net domain there? Let me know so we can start serving the docs in the new way because it will be way easier to keep everything up to date. 

Thanks for taking the time to do this whole thing, it wouldn't be possible without your help.

**Comment by seleb** [comment]
You can serve the docs directly from the main branch, yeah. Here's an example of what the settings should look like for that to work:

image

And happy to help!

**Comment by seleb** [comment]
OK, i think this is ready to go! there's definitely still room for improvement (there's quite a lot of redundancy between `dev-only`, `docs/examples`, and `RenJSQuickstart_V2`), but that's all stuff that can be iterated on once the release process itself is verified to be working as expected.

Note that there are no conventional commits in this PR, so we should not expect a release to be triggered when it is merged. Once it's merged, an empty commit with `fix:` or `feat:` could be pushed to test it out.

**Pull request merged**
